trigger:
- master

variables:
  buildConfiguration: Release

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        arguments: '-c $(buildConfiguration) -o $(System.DefaultWorkingDirectory)/publish'

    - publish: publish
      artifact: function

- stage: Deploy
  dependsOn:
  - Build
  jobs:
  - job: Deploy
    pool:
      vmImage: 'windows-2019'
    steps:
      - checkout: none
      - download: current