# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  buildConfiguration: Release

pool:
  vmImage: 'windows-2019'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '-c $(buildConfiguration) -o $(System.DefaultWorkingDirectory)/publish'

- publish: publish
  artifact: function